### ISSUE TITLE
Easier to navigate between pages

### ISSUE THREAD

**Issue by TheSweMaster** [Yakimych/result-log#39]
I have a suggestion that will make it easier to navigate between pages in the application.

Today the "Start Page" and "All Result" links are in the bottom of the list of matches, this makes it difficult to go back when the list gets longer.
Example: 
![Example startpage issue](https://user-images.githubusercontent.com/23028331/63779823-81ab5280-c8e7-11e9-9925-8b6a000edfee.JPG)

Suggestion: To make the start page link static on the top left corner of the page like on the ~/history page.

**Comment by Yakimych** [comment]
Yes, good idea! I am considering some kind of a Nav-bar on top, that would have links to the "Start Page", "Weekly Leaderboard" and "Result History" pages. It is probably going to be part of the Styling issue (https://github.com/Yakimych/result-log/issues/25).

**Comment by Yakimych** [comment]
Fixed in https://github.com/Yakimych/result-log/pull/44 and https://github.com/Yakimych/result-log/commit/6a5a15be9341dec17eea6750a9bfa469997158fc
